### ISSUE TITLE
amend manual for SF format

### ISSUE THREAD

**Issue by lduvaux** [alachins/sweed#2]
Hi,

reading the manual, I got trouble to properly format my data to SF format. It would be good to correct/says the following things:
- columns have to be separated by tabulations
- the first header is "position" and not "location" (this cause me some trouble with the program)
- the program does not supports gz compressed files

Thanks

**Comment by alachins** [comment]
Thanks for the suggestions.

We are going to include them in the next release of the manual.

Nikos
