### ISSUE TITLE
Same number of significant regions in different populations

### ISSUE THREAD

**Issue by DuttaAnik** [alachins/sweed#22]
Hello,

I am running SweeD with version 3.3.2. I have made individual vcf files for each chromosome and I am running SweeD for each chromosome+population separately. I am setting the significance threshold manually at 99.5%.

But the problem is, for all the populations after combining the chromosome in one file, the number of significant regions under selection is the same. I checked the positions and they are different in different populations. But why do I obtain the same number of significant positions in different populations?

Can you please tell me if it is normal or not?

Thank you.

**Comment by alachins** [comment]
I have replied to your email.
