### ISSUE TITLE
The manual is missing from Sweed web page

### ISSUE THREAD

**Issue by molpopgen** [alachins/sweed#3]
The [url](https://sco.h-its.org/exelixis/countSweepManual.php) given [here](http://pop-gen.eu/wordpress/software/sweed) is incorrect, and result in page not found.

**Comment by alachins** [comment]
Hi there,

The manual is available here:
https://github.com/alachins/sweed/blob/master/sweed3.0_manual.pdf

Best regards,
Nikos
