### ISSUE TITLE
a wrong infomation happen

### ISSUE THREAD

**Issue by xiaolongtu** [alachins/sweed#9]
hi proffessor, i find a problem when use web https://cme.h-its.org/exelixis/resource/download/data/SweeD_DATA_SCRIPTS.tar.bz2 , show "You don't have permission to access /exelixis/resource/download/data/SweeD_DATA_SCRIPTS.tar.bz2 on this server."  could you please send me this data ,my email address : 757427796@qq.com
thank you !

**Comment by alachins** [comment]
hello, the data you are asking for have probably been removed from that server. In any case, SweeD has gone through several revisions/releases since then, and even if you were able to find those files somewhere, you wouldn t be able to successfully run SweeD. We can help if you described what you are trying to do.
Nikos

**Comment by xiaolongtu** [comment]
thanks profeddor
I do meet some trouble, I use sweed to get select sweeps in my paper, now i received the reviewer response, i need "Simulating data under that demographic model and get null distribution".  I read sweed manual again, but still had  some confusion.  
1. if I use dadi to get simulating demographic model with SFS . this step we could get theta, migaration, split time and Ne. use these data in follow command line to simulate a sfs file.
" SweeD -name test  -s sample size -osfs SweeD_name.SFS -eN 0.0375 0.01 -eN 0.03875 1.0 "
 or  "java -Xmx125000M -jar msms.jar -N theta  -ms sample size  1000  -s S -r 5000 5000  -oSFS SweeD_name.SFS "
2. if I use upper steps' sfs file to run sweed , is top 1% the neutral theshold ?  " ./SweeD -name test -input data.FA -grid 15 -isfs  SweeD_name.SFS",  
could you please help me , I am a little worry.

**Comment by xiaolongtu** [comment]
> hello, the data you are asking for have probably been removed from that server. In any case, SweeD has gone through several revisions/releases since then, and even if you were able to find those files somewhere, you wouldn t be able to successfully run SweeD. We can help if you described what you are trying to do.
> Nikos
thanks professor
I do meet some trouble, I use sweed to get select sweeps in my paper, now i received the reviewer response, i need "Simulating data under that demographic model and get null distribution". I read sweed manual again, but still had some confusion.

if I use dadi to get simulating demographic model with SFS . this step we could get theta, migaration, split time and Ne. use these data in follow command line to simulate a sfs file.
" SweeD -name test -s sample size -osfs SweeD_name.SFS -eN 0.0375 0.01 -eN 0.03875 1.0 "
or "java -Xmx125000M -jar msms.jar -N theta -ms sample size 1000 -s S -r 5000 5000 -oSFS SweeD_name.SFS "
if I use upper steps' sfs file to run sweed , is top 1% the neutral theshold ? " ./SweeD -name test -input data.FA -grid 15 -isfs SweeD_name.SFS",
could you please help me , I am a little worry.

**Comment by xiaolongtu** [comment]
thanks professor
I do meet some trouble, I use sweed to get select sweeps in my paper, now i received the reviewer response, i need "Simulating data under that demographic model and get null distribution". I read sweed manual again, but still had some confusion.

first, if I use dadi to get simulating demographic model with SFS . this step we could get theta, migaration, split time and Ne. use these data in follow command line to simulate a sfs file.
" SweeD -name test -s sample size -osfs SweeD_name.SFS -eN 0.0375 0.01 -eN 0.03875 1.0 "
or "java -Xmx125000M -jar msms.jar -N theta -ms sample size 1000 -s S -r 5000 5000 -oSFS SweeD_name.SFS "
second, if I use upper steps' sfs file to run sweed , is top 1% the neutral theshold ?
 " ./SweeD -name test -input data.FA -grid 15 -isfs SweeD_name.SFS";

could you please help me , I am a little worry.

**Comment by alachins** [comment]
I think the reviewer is asking to generate neutral simulated datasets the demographic model of your test data, and process them with SweeD to get the x% neutral threshold. Then analyze your test data, apply the threshold, and look at the points that exceed the threshold as candidate sweep regions.

**Comment by xiaolongtu** [comment]
So, could you please  teach me  how to get  neutral simulated datasets ?

**Comment by alachins** [comment]
you can use Hudson's ms tool. Go through the manual to see what parameters you can provide to describe the demographic model you have. start with that.

**Comment by xiaolongtu** [comment]
as follow commond ? the  parameters i need provide is from dadi or GPhoCS ?
 java -Xmx125000M -jar msms.jar -N theta -ms sample size 1000 -s S -r 5000 5000 -eN 0.0375 0.01 -eN 0.03875 1.0"

**Comment by xiaolongtu** [comment]
hi, sir
&nbsp;&nbsp;I had run msms with population model to get ms -format &nbsp;file . now, &nbsp;for sweed, there are two questions
&nbsp;first , the 1st column of the sweed's result is position, this is decided by parameter grid number, so different grid number got different position, for this result ,how to know exactly where is seletive sweeps &nbsp; from genome with different grid number ?


secnod , &nbsp;when use ms-file which is from ms to sweed, how to set grid and length &nbsp;value&nbsp;
SweeD -name &nbsp;runname -input &nbsp;xx.ms &nbsp;-grid xx &nbsp;-length xxx
t
hank you !




--------------&nbsp;原始邮件&nbsp;------------------


发件人:&nbsp;"alachins"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 晚上10:17
收件人:&nbsp;"alachins/sweed"<sweed@noreply.github.com&gt;;
抄送:&nbsp;"浮光掠影"<757427796@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alachins/sweed] a wrong infomation happen (#9)




you can use Hudson's ms tool. Go through the manual to see what parameters you can provide to describe the demographic model you have. start with that.
